### ISSUE TITLE
mpi4py-fft, array storage

### ISSUE THREAD

**Issue by apatlpo** [mpi4py/mpi4py-fft#1]
Would there be any sense for mpi4py-fft to provide methods for storing arrays in physical or spectral spaces and under various formats (hdf, netcdf or other) ?

I was playing with mpi4py-fft and wished there was such feature.

cheers

**Comment by mikaem** [comment]
Hi Aurélien,
Thanks for the feedback:-) We have actually been considering this, but for now we have decided to keep mpi4py-fft to do only the MPI and the transforms. Users of mpi4py-fft, like shenfun and spectralDNS, implement the IO. But the TensorProductSpace class of shenfun is very similar to the PFFT class of mpi4py-fft, and the [h5py_writer](https://github.com/spectralDNS/shenfun/blob/master/shenfun/utilities/h5py_writer.py) and [nc_writer](https://github.com/spectralDNS/shenfun/blob/master/shenfun/utilities/nc_writer.py) of shenfun could be reused with very little modification. Then again, mpi4py-fft is a more generic tool and could be used by others. So perhaps the right thing to do would be to implement basic IO tools in mpi4py-fft that could be easily overloaded with more advanced methods by users? I'm thinking that TensorProductSpace could be made a subclass of PFFT, and then it would fall more naturally into place. At least some reorganisation seems to be in order:-)

**Comment by mikaem** [comment]
Hi
I have now added some IO classes under utilities. I added NetCDF4 as well. Please feel free to check it out. Not quite sure if I have chosen the best possible strategy for storing slices so I would appreciate any feedback:-)
Note, I could open and view the NetCDF4 files using Visit, but I had no luck with Paraview. Is that the same for you?
