### ISSUE TITLE
mpi4py-fft and numpy differ for a noisy field

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#10]
I have been converting some numpy based fft code to mpi4py-fft and finding some odd results.  When I choose the initial field to be random, as one does, I get that the derivatives in the x-directions match very well, but the derivatives in the y-directions are rather different.  

Question: should they yield the same results and if yes why are these results different?

`import numpy as np
from numpy.fft import fftn, ifftn
import sys
from mpi4py import MPI
from mpi4py_fft import PFFT, newDistArray
from mpi4py_fft.fftw import rfftn, irfftn

import matplotlib.pyplot as plt

def get_local_mesh(FFT, L):
    """Returns local mesh."""
    X = np.ogrid[FFT.local_slice(False)]
    N = FFT.global_shape()
    for i in range(len(N)):
        X[i] = (X[i]*L[i]/N[i])
    X = [np.broadcast_to(x, FFT.shape(False)) for x in X]
    return X

def get_local_wavenumbermesh(FFT, L):
    """Returns local wavenumber mesh."""
    s = FFT.local_slice()
    N = FFT.global_shape()
    # Set wavenumbers in grid
    k = [np.fft.fftfreq(n, 1./n).astype(int) for n in N[:-1]]
    k.append(np.fft.rfftfreq(N[-1], 1./N[-1]).astype(int))
    K = [ki[si] for ki, si in zip(k, s)]
    Ks = np.meshgrid(*K, indexing='ij', sparse=True)
    Lp = 2*np.pi/L
    for i in range(2):
        Ks[i] = (Ks[i]*Lp[i]).astype(float)
    return [np.broadcast_to(k, FFT.shape(True)) for k in Ks]

def main():

    # Grid Parameters                                                
    M = 3
    N = np.array([2**M, 2**M],       dtype=int)
    L = np.array([np.pi, np.pi], dtype=float)
    dx = L/N

    # Create parallel FFT
    #r2c = PFFT(MPI.COMM_WORLD, N, axes=(0, 1), dtype=np.float,
    #           grid=(-1,), transforms={(0,1): (rfftn, irfftn)} )
    r2c = PFFT(MPI.COMM_WORLD, N)

    # Declare variables
    pr   = newDistArray(r2c, False)      
    qr   = newDistArray(r2c, False)      
    er   = newDistArray(r2c, False)      
    rr   = newDistArray(r2c, False)      
    qk   = newDistArray(r2c)      
    fk   = newDistArray(r2c)      

    # Grid and wavenumber
    X    = get_local_mesh(r2c, L)
    K    = get_local_wavenumbermesh(r2c, L)
    K    = np.array(K).astype(float)

    # Initial Conditions
    np.random.seed(1)
    qr[:] = 2.0*(np.random.random(qr.shape).astype(qr.dtype)-0.5)

    ### Method 1: compute gradient using mpi4py-fft

    qk = r2c.forward(qr)
    fk = 1j*K[1]*qk
    pr = r2c.backward(fk, pr)

    qk = r2c.forward(qr)
    fk = 1j*K[0]*qk
    rr = r2c.backward(fk, rr)

    print('Method 1: mpi4py-fft (extreme values)')
    print('q_x:', np.amin(pr), np.amax(pr))
    print('q_y:', np.amin(rr), np.amax(rr))
    print(' ')
    
    ### Method 2: compute gradient using numpy fft

    # Grid
    x = np.linspace(0,L[0]-dx[0],N[0])
    y = np.linspace(0,L[1]-dx[1],N[1])
    xx,yy = np.meshgrid(x,y)

    # Wavenumber
    kx = 2*np.pi/L[0]*N[0]*np.fft.fftfreq(N[0])
    ky = 2*np.pi/L[1]*N[1]*np.fft.fftfreq(N[1])
    kxx, kyy = np.meshgrid(kx,ky)

    # Initial Conditions
    np.random.seed(1)
    q  = 2.0*(np.random.random((N[1],N[0])) - 0.5)

    q_hat = fftn(q)
    q_x = (ifftn( 1j*kxx*q_hat)).real
    q_y = (ifftn( 1j*kyy*q_hat)).real

    print('Method 2: numpy (extreme values)')
    print('q_x:', np.amin(q_x), np.amax(q_x))
    print('q_y:', np.amin(q_y), np.amax(q_y))
    print(' ')

    print('Good news: q_x are almost identical')
    print('Bad news:  q_y are very different')

main()
`

**Comment by mikaem** [comment]
Hi Francis,

Yes, numpy and mpi4py-fft should give the same result. But you are using rfftn/irfftn for mpi4py-fft and fftn/ifftn for numpy. Normally that's not a problem, but you have to do it correctly, and for that you have to know what is going on under the hood. When a real array X is transformed (with rfftn) you get a complex array Y with Hermitian symmetry. See, e.g., [here](https://docs.scipy.org/doc/numpy/reference/routines.fft.html#module-numpy.fft). For this transformed array item Y[N/2+1] will be real. Problem is that when you multiply this same array with k*1j, then Y[N/2+1] will become complex and not real. And when you do irfftn(1j*k*rfftn(x)), then irfftn assumes that it is transforming a complex array with Hermitian symmetry and assumes item N/2+1 is real. Since it is actually now complex it is treated as zero and that is why you get a difference between irfftn and ifftn (not mpi4py-fft and numpy). If you do numpy with rfftn/irfftn as well, then you should get the same results.

**Comment by francispoulin** [comment]
Hello Mikael,

Ah, that makes sense.  Thanks!  I can confirm that when I use rfftn in numpy I do get the same result.
One last question, with this issue I hope, does that mean to maintain the symmetry we should multiply the last entry by k1 instead of k1j, to keep it real?

**Comment by mikaem** [comment]
No. You should set it to 0, but only for N even. For N odd you don't have to do anything. Takes a while to explain, but you could search for Fourier interpolator. Trefethen's 'spectral methods for matlab' has a decent explanation and so does most textbooks on spectral methods.

**Comment by francispoulin** [comment]
Thanks.  I tried playing with that and didn't have success but will keep at it.  I know Trefethen's book quite well from my doctoral days but clearly need to brush up on it.  Thanks for the reference.

On a related note, when I comment out the PFFT line and uncomment this, which I think uses the fftn and ifftn, I still get the same results.  I still have that the transformed arrays are not square. How should I change the syntax to get the c2c transforms?

`r2c = PFFT(MPI.COMM_WORLD, N, axes=(0, 1), dtype=np.float,
#           grid=(-1,), transforms={(0,1): (rfftn, irfftn)} )`

**Comment by mikaem** [comment]
Use 'dtype=np.complex'

**Comment by francispoulin** [comment]
That makes sense, and I did try that but then it seems I have to define the wavenmbers differently.  I guess the get_local_wavenumbermesh assumes it's going to be using r2c.  Does that make sense?

`Traceback (most recent call last):
  File "example2.py", line 124, in <module>
    main()
  File "example2.py", line 61, in main
    K    = get_local_wavenumbermesh(r2c, L)
  File "example2.py", line 33, in get_local_wavenumbermesh
    return [np.broadcast_to(k, FFT.shape(True)) for k in Ks]
  File "example2.py", line 33, in <listcomp>
    return [np.broadcast_to(k, FFT.shape(True)) for k in Ks]
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/home/fpoulin/software/anaconda3/envs/mpi4py-fft/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/fpoulin/software/anaconda3/envs/mpi4py-fft/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 125, in _broadcast_to
    it = np.nditer(
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (1,5) and requested shape (8,8)
`

**Comment by mikaem** [comment]
Yes, that is correct. Use fftfreq for both directions.

**Comment by francispoulin** [comment]
Thanks!  I simply changed the rfft to fft and I can confirm that it does yield the correct answer.
I will try and get the rfft working as that is the better way to go but I am happy to say that I am getting agreement.

I will close this ticket.

From,

`k.append(np.fft.rfftfreq(N[-1], 1./N[-1]).astype(int))`

to,

`k.append(np.fft.fftfreq(N[-1], 1./N[-1]).astype(int))`
