### ISSUE TITLE
How to redistribute an already declared array?

### ISSUE THREAD

**Issue by DenTyur** [mpi4py/mpi4py-fft#32]
Hello, Mikaem!

In the Parallel FFT examples in the documentation, a distributed array is always created first, and then filled with numbers (in this case, random numbers). For instance:
```
N = np.array([128, 128, 128], dtype=int)
fft = PFFT(MPI.COMM_WORLD, N, axes=(0, 1, 2), dtype=np.float, grid=(-1,))
u = newDistArray(fft, False)
u[:] = np.random.random(u.shape).astype(u.dtype)
```
Can you please tell me how to create a numpy array first and then redistribute it for parallel FFT?

**Comment by mikaem** [comment]
Hi
It is not possible. mpi4py-fft is only ment to be used for distributed arrays and not for shared memory.
