### ISSUE TITLE
How to fill a distributed array with function values?

### ISSUE THREAD

**Issue by DenTyur** [mpi4py/mpi4py-fft#33]
Hello!

I'm just starting to study your library, so my question may seem naive.
But how to fill a distributed array with function values correctly? For example, there is a coordinate grid (NxN) on which the values of the function are set. I want to do a Fourier transform for this function. With `newDistArray`, I can create a distributed array of full dimension (NxN). And how to fill it with function values after that?

I could create a distributed array for the coordinate grid, then pass it as an argument to the function and as a result get a distributed array with the values of the function. 
But then the question arises, how to fill in a distributed array for a coordinate grid?

How to approach this problem correctly?
(Something similar is being done in your example `spectral_dns_solver.py`, but I haven't fully figured out this code)

I will be glad to your comments!

**Comment by mikaem** [comment]
Hi
To me it sounds like `spectral_dns_solver.py` is exactly what you need to understand this. In this solver we initialize the solution as 

```
u = sin(x) cos(y) cos(z)
v = -cos(x) sin(y) cos(z)
w = 0
```

To this end we use the [distributed mesh](https://github.com/mpi4py/mpi4py-fft/blob/291e327fa7c7a10675e97f888eeda7b79e5aa567/examples/spectral_dns_solver.py#L67) X:

```python
X = get_local_mesh(FFT, L)
U[0] = np.sin(X[0])*np.cos(X[1])*np.cos(X[2])
U[1] = -np.cos(X[0])*np.sin(X[1])*np.cos(X[2])
U[2] = 0
```
Here `U` is distributed, using the part of the mesh that belongs to its processor only.

**Comment by DenTyur** [comment]
Thanks for the answer!
