### ISSUE TITLE
docs lead to ImportError

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#4]
Hello

I am brand new to mpi4py-fft and have read through the documents and now wanting to try out the different examples to learn from experience.  Unfortunately, one of the first importing steps seems to fail. My library claims to be successfully installed. Does this mean I have a faulty installation?

Francis

`>>> from mpi4py_fft import Pencil, Subcomm

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: cannot import name 'Pencil'
`

**Comment by mikaem** [comment]
Hi Francis

What it means is that the developers have been lazy using untested code in documentation! The line should be

`from mpi4py_fft.pencil import Pencil, Subcomm`

Please let us know if there are any other code snippets in the documentation that don't work.

**Comment by francispoulin** [comment]
Hello Mikael,

Thanks for correcting that for me. I can say that I have tried it and it does work.  I plan to go through all the other examples in the documentation and make sure that work.  All except for the ones involving h5py, since I can't seem to get h5pyp installed and their developers aren't getting back to me on that.   

I will close this for now and open it up again if/when I find other problems in the docs.

P.S. I would say more busy developers.
