### ISSUE TITLE
Problem in slab decomposition docs

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#5]
From following the slab decomposition docs I have the file pfft_example.py, which is copied below.  When I run it with two cores I get a slightly different output from what is suggested.

`1 (64, 128, 128)
0 (64, 128, 128)
1 (128, 32, 128)
0 (128, 33, 128)
`

It does run but I imagine the output should be modified slightly to reflect this difference.

`import numpy as np
from mpi4py import MPI
from mpi4py_fft import PFFT, newDistArray
N = np.array([128, 128, 128], dtype=int)
#fft = PFFT(MPI.COMM_WORLD, N, axes=(0, 1, 2), dtype=np.float, grid=(-1,))
fft = PFFT(MPI.COMM_WORLD, N, axes=(2, 0, 1), dtype=np.float)

u = newDistArray(fft, False)
u[:] = np.random.random(u.shape).astype(u.dtype)
u_hat = fft.forward(u, normalize=True) # Note that normalize=True is default and ca
n be omitted
uj = np.zeros_like(u)
uj = fft.backward(u_hat, uj)
assert np.allclose(uj, u)
print(MPI.COMM_WORLD.Get_rank(), u.shape)

u_hat = newDistArray(fft, True)
print(MPI.COMM_WORLD.Get_rank(), u_hat.shape)
`

**Comment by mikaem** [comment]
Thanks Francis,

Good catch:-) This behaviour probably changed when we introduced the grid parameter. You can get the old behaviour using `grid=(1, 1, -1)`, such that the input array is distributed along the last axis. I'll fix the docs accordingly.

**Comment by francispoulin** [comment]
Thanks for recognizing the problem and finding an easy fix.  I tried it and, as you know very well, it produces exactly what you suggested.  I will close this up and let you know if I have any other suggestions with the docs.
