### ISSUE TITLE
more cores takes longer

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#6]
I have put together a simple code from the codes that will time how long it takes the compute the forward and inverse transforms of a matrix 100 times. 

When I do tests on my laptop (4 cores) I get that with more cores the code actually slows down.

This is run using: mpiexec -np 4 python pfft_2d.py

np = 1     37 sec
np = 2     48 sec
np = 4     49 sec

I am surely doing something wrong and would really appreciate how I can fix my code to get some speed up instead slow down.

`import numpy as np
import timeit
import sys

SETUP_CODE = '''
import numpy as np
from mpi4py import MPI
from mpi4py_fft import PFFT, newDistArray

nx = 4096
N = np.array([nx, nx], dtype=int)
fft = PFFT(MPI.COMM_WORLD, N, axes=(0, 1), dtype=np.float, grid=(-1,))

u = newDistArray(fft, False)
u[:] = np.random.random(u.shape).astype(u.dtype)
'''

TEST_CODE = '''
u_hat = fft.forward(u) 
uj = np.zeros_like(u)
uj = fft.backward(u_hat, uj)
'''

times = timeit.timeit(setup = SETUP_CODE,
                      stmt = TEST_CODE,
                      number = 100)

print('Time = %6.4f seconds' % times)
`

**Comment by mikaem** [comment]
Hi Francis,

Laptops were not really built for distributed memory MPI and they do not have very fast communication channels between the cores. So it's not very surprising that highly communication heavy tasks (that need to send a lot of data between cores), like the FFT, scale poorly on a laptop. However, on my MAC your code times in at 62, 45 and 31 seconds using 1, 2 and 4 cores, so you should perhaps consider a new laptop:-) Perfect scaling is really only to be expected on computers built for MPI, like the Cray XC we use for testing in our paper [Fast parallel multidimensional FFTs using advanced MPI](https://www.sciencedirect.com/science/article/pii/S074373151830306X).

**Comment by francispoulin** [comment]
Hello Mikael,

Thanks for the feedback. I agree that laptops are not ideal for measuring scalability but thought it would do a decent job.  Now I know that at least my laptop is pretty bad for that and will continue doing my testing on one of our clusters that's designed for computing.

I did some tests just now and found some much better results.

N = 1024
np = 1,  time = 5.7, 
np = 2,  time = 3.2, efficiency = 90%
np = 4,  time = 1.7, efficiency = 84%
np = 8,  time = 0.75, efficiency = 95%

N = 4096
np = 1,  time = 154,
np = 2,  time = 75, efficiency = 100%
np = 4,  time = 39,  efficiency = 99%
np = 8,  time = 22,  efficiency = 88%
np =16, time = 12, efficiency =  80%

Things get worst for np = 32 but this has more to do with the server getting full.

I am glad to see that I am getting good performance.  Thank you!

I am going to close this issue but now work on making the fftw's more efficient for a given problem.  I may ask for help with that as well, since I'm very new to this as well.

Cheers, Francis
