### ISSUE TITLE
reading in h5 file

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#8]
I am following section 1.5 of the docs to read in an h5 file and everything does seem to work well.  But I do have questions about some of the details.

- It seems that we need the transform type, what is called T in the example. Is this really necessary?
- In the example, you need to define the grid, then then the transform, and then you read in the array.  Can you read in the array and then figure that out?
- Also, in addition to figuring out the grid, can you figure out the number of time steps that are stored?

**Comment by mikaem** [comment]
Hi Francis,

> It seems that we need the transform type, what is called T in the example. Is this really necessary?

You need T to create `DistArray`'s. We store to file using the `write` method of the `DistArray`.

> In the example, you need to define the grid, then then the transform, and then you read in the array. Can you read in the array and then figure that out?

Yes you can. All the information is in the HDF5-file.

> Also, in addition to figuring out the grid, can you figure out the number of time steps that are stored?

Yes. I take it you're not very used to inspecting HDF5-files? The easiest approach outside of Python is to use [HDFView](https://www.hdfgroup.org/downloads/hdfview/). There's also a bunch of [command line tools](https://support.hdfgroup.org/products/hdf5_tools/). In Python you can just open the file and inspect it. Lots of different options, to get a list of all the datasets you can do

    import h5py
    f = h5py.File('filename.h5', 'r')
    items = []
    f.visit(items.append)
    print(items)

**Comment by francispoulin** [comment]
After having learned netcdf a little, I am now learning hdf5 and it's going slowly.  Sorry for the bother but thank you for the help.  I will work with that and should be able to sort it out.

**Comment by francispoulin** [comment]
In case others might benefit from this, I have copied a script below that can get basic information from an h5 file created using this library.

`import numpy as np
import h5py
import sys

"""
Structure of h5 file:

/Ar
  /2D
     /0
     /1
     ...
     /100
  /domain
     /x0
     /x1

To list all groups run the following after opening file

def printname(name):
    print(name)

f.visit(printname)
"""

f = h5py.File('filename.h5', 'r')            # open file

keys = list(f.keys())                        # list variables

print('Variables:')                          
for key in keys:
    print('     ', key)

var1 = keys[0]
L0 = np.array(f[var1 + '/domain/x0'][()])       # bounds in 0-axis
L1 = np.array(f[var1 + '/domain/x1'][()])       # bounds in 1-axis

print('Lengths of domain:')
print('      x0 in [%6.4f, %6.4f]' % (L0[0], L0[1]))
print('      x1 in [%6.4f, %6.4f]' % (L1[0], L1[1]))

f0 = np.array(f[var1 + '/2D/0'][()])            # read in initial array
N = f0.shape

print('Resolutions:')
print('    (Nx,Ny) = (%d, %d)' % (N[0], N[1]))

timeindex = np.array(f[var1 + '/2D'])           # indices in time
Nt = len(timeindex)

print('Outputs in time:')
print('      Nt    = ', Nt)
`

**Comment by francispoulin** [comment]
I have a question about how to write to the h5 file.

In the domain variable there is a variable for each direction, x0 and x1 say, and in each of these we store the extreme values in that direction.  It seems like the default values are 0 and 2*pi.  

How do I write diferent values into these variables?

Sorry that it's not obvious to me as I only write the variables and that seems to do most of it for me.

**Comment by francispoulin** [comment]
Sorry to bother you but wanted to check in to see whether you might have any advice on how to write the domain lengths to the h5 file?

**Comment by mikaem** [comment]
Hi
See [the signature](https://github.com/mpi4py/mpi4py-fft/blob/8f37fa3e85a60d31dd9517907dec22835af0e662/mpi4py_fft/io/file_base.py#L8). You give the domain when the file is created. Either as a 2-tuple or as two arrays (for when the mesh is nonuniform)

**Comment by francispoulin** [comment]
Thanks!

Yes, that did the trick.  I did something like the following and it worked beautifully.

`    f0 = HDF5File('filename.h5', mode='w', domain=((0,L[0]),(0,L[1]))) `
