### ISSUE TITLE
doing multiple transforms together

### ISSUE THREAD

**Issue by francispoulin** [mpi4py/mpi4py-fft#9]
I am trying to improve the efficiency of my code that uses mpi4py-fft but having problems with accuracy.  Basically, I want to compute the gradient of a vorticity vector and then invert to compute the velocity.  I hoped that I could do one 2D forward transform and then many derivatives without having to store too much. Below tries to compute psi_y*q_x where q is the vorticity.  

What is weird is that if I uncomment the 4th line I get a different answer, which suggests to me that qk changes somewhere in either line 2 or 3.  Can you help me to understand what's happening?

    qk = fft.forward(qr)
    fk = -ikyoK2*qk
    fr = fft.backward(fk, fr)
    
    #qk = fft.forward(qr)
    fk =  ikx*qk
    gr = fft.backward(fk, gr)

**Comment by mikaem** [comment]
Hi Francis
Could you post a working example? Makes it much easier to assist. There's nothing going on on lines 2 to 3 to change qk. 

When it comes to efficiency and cross products (like the curl) there is a big advantage going to numba or Cython. See [this paper](https://arxiv.org/pdf/1602.03638v1.pdf), especially sec 3.4.

**Comment by francispoulin** [comment]
Hello Mikael,

I am including a sample code that produces the problem that I mentioned.  Sorry that I didn't think about doing this myself.

Thanks also for sending me the link to your paper.  I will read it soon.

`import numpy as np

from mpi4py import MPI
from mpi4py_fft import PFFT, newDistArray
from mpi4py_fft.fftw import rfftn, irfftn

def get_local_mesh(FFT, L):
    """Returns local mesh."""
    X = np.ogrid[FFT.local_slice(False)]
    N = FFT.global_shape()
    for i in range(len(N)):
        X[i] = (X[i]*L[i]/N[i])
    X = [np.broadcast_to(x, FFT.shape(False)) for x in X]
    return X

def get_local_wavenumbermesh(FFT, L):
    """Returns local wavenumber mesh."""
    s = FFT.local_slice()
    N = FFT.global_shape()
    # Set wavenumbers in grid
    k = [np.fft.fftfreq(n, 1./n).astype(int) for n in N[:-1]]
    k.append(np.fft.rfftfreq(N[-1], 1./N[-1]).astype(int))
    K = [ki[si] for ki, si in zip(k, s)]
    Ks = np.meshgrid(*K, indexing='ij', sparse=True)
    Lp = 2*np.pi/L
    for i in range(2):
        Ks[i] = (Ks[i]*Lp[i]).astype(float)
    return [np.broadcast_to(k, FFT.shape(True)) for k in Ks]


def main():

    # Grid Parameters                                                
    M = 4 
    N = np.array([2**M, 2**M],       dtype=int)
    L = np.array([np.pi, np.pi], dtype=float)
    dx = L/N

    # Create parallel FFT
    r2c = PFFT(MPI.COMM_WORLD, N, axes=(0, 1), dtype=np.float,
               grid=(-1,), transforms={(0,1): (rfftn, irfftn)} )

    # Declare variables
    pr   = newDistArray(r2c, False)      
    qr   = newDistArray(r2c, False)      
    rr   = newDistArray(r2c, False)      
    qk   = newDistArray(r2c)      
    fk   = newDistArray(r2c)      

    # Grid and wavenumber
    X    = get_local_mesh(r2c, L)
    K    = get_local_wavenumbermesh(r2c, L)
    K    = np.array(K).astype(float)

    # Initial Conditions
    np.random.seed(1)
    qr[:] = 2.0*(np.random.random(qr.shape).astype(qr.dtype)-0.5)

    ### Method 1

    qk = r2c.forward(qr)
    fk = 1j*K[0]*qk
    pr = r2c.backward(fk, pr)

    qk = r2c.forward(qr)
    fk = 1j*K[1]*qk
    rr = r2c.backward(fk, pr)

    print('Method 1: extreme values')
    print(np.amin(rr), np.amax(rr))
    print(' ')
    
    ### Method 2: like 1st but does not recompute qk

    qk = r2c.forward(qr)
    fk = 1j*K[0]*qk
    pr = r2c.backward(fk, pr)

    #qk = r2c.forward(qr)
    fk = 1j*K[1]*qk
    rr = r2c.backward(fk, pr)

    print('Method 2: extreme values')
    print(np.amin(rr), np.amax(rr))
    print(' ')

    print('Above values should be identical but are not.')
    
main()`

**Comment by francispoulin** [comment]
Were you able to reproduce this result?

**Comment by mikaem** [comment]
Yes, I reproduced it. But in the future, if you could try to indent all code in these boxes with 4 spaces, it would make it look nicer and it's more straightforward to copy and paste😃 Use the preview button to check how it will look.

**Comment by francispoulin** [comment]
Of courses and very sorry. I will do that and even went back to clean it up to learn how and try and get into the habit.  Can't do the first line but oh well.

**Comment by francispoulin** [comment]
Any idea how to fix this issue?

**Comment by mikaem** [comment]
I didn't realise there was still an issue?

**Comment by francispoulin** [comment]
Unfortunately, I still get the same result after trying it just now.  It seems that qk gets changed after computing the transform or backwards transform, or something.

**Comment by mikaem** [comment]
Yes, I see it now. If you don't give r2c.forward an output array, the one returned is r2c's internal output array. That one will be overwritten on consecutive calls. The solution is to use call

    qk = r2c.forward(qr, qk)

Like you do for some, but not all transforms.

**Comment by francispoulin** [comment]
Ah, that makes a lot of sense.  Thank you!

I can confirm that I do get the correct answer.

Moreover, I hope that I have learned better programming style as having the second argument clearly can help sometimes, and I will try and stick to that in the future.
